### ISSUE TITLE
Error in csUTh

### ISSUE THREAD

**Issue by MichelineCampbell** [tonydoss/UThwigl#22]
Hi,
I found a bug in the csUTh function that means the detrital correction doesn't work.  

Line 53 of the function:

```    if (detcorrection == "Y") {```

should be:

```     if (detcorrection == TRUE) {``` to align with function parameter inputs.

Thanks for the package!

**Comment by benmarwick** [comment]
Thanks so much for spotting that mistake and letting us know! I've fixed it now.

**Comment by MichelineCampbell** [comment]
Thank-you! I'd have done a pull request and fixed it myself but I'm useless with git, sorry.
